spring:
  application:
    name: homecraft-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/homecraft_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Changed from 'update' to 'create' to recreate tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kavishkadewduni@gmail.com
    password: jvbs ynfx rbgi yorb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

logging:
  level:
    com.homeservice: DEBUG
    org.springframework.security: DEBUG